-- Generated by local/generate-fixtures.cjs. Synthetic local data only. Idempotent.
BEGIN;
INSERT INTO organisation (id, code, kind, legal_name) VALUES
  ('00000000-0000-4000-b000-000000000001', 'NOVA', 'manufacturer', 'Nova Cool Appliances Pvt Ltd (synthetic)'),
  ('00000000-0000-4000-b000-000000000002', 'PIXEL', 'agency', 'PixelCert Agency (synthetic)'),
  ('00000000-0000-4000-b000-000000000003', 'BEE', 'bee', 'Bureau of Energy Efficiency (local)'),
  ('00000000-0000-4000-b000-000000000004', 'IAME', 'iame', 'IAME Local Panel (synthetic)'),
  ('00000000-0000-4000-b000-000000000005', 'SDA', 'sda', 'State Designated Agency (synthetic)'),
  ('00000000-0000-4000-b000-000000000006', 'LAB', 'laboratory', 'Synthetic Test Laboratory')
ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, kind = EXCLUDED.kind, legal_name = EXCLUDED.legal_name, status = 'active';
INSERT INTO user_account (id, keycloak_subject, username, display_name) VALUES
  ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-a000-000000000001', 'nova.applicant', 'Nova Applicant'),
  ('00000000-0000-4000-a000-000000000002', '00000000-0000-4000-a000-000000000002', 'pixel.applicant', 'Pixel Applicant'),
  ('00000000-0000-4000-a000-000000000003', '00000000-0000-4000-a000-000000000003', 'bee.finance', 'BEE Finance'),
  ('00000000-0000-4000-a000-000000000004', '00000000-0000-4000-a000-000000000004', 'iame.officer', 'IAME Officer'),
  ('00000000-0000-4000-a000-000000000005', '00000000-0000-4000-a000-000000000005', 'bee.reviewer', 'BEE Reviewer'),
  ('00000000-0000-4000-a000-000000000006', '00000000-0000-4000-a000-000000000006', 'bee.programme', 'BEE Programme'),
  ('00000000-0000-4000-a000-000000000007', '00000000-0000-4000-a000-000000000007', 'bee.director', 'BEE Director'),
  ('00000000-0000-4000-a000-000000000008', '00000000-0000-4000-a000-000000000008', 'bee.secretary', 'BEE Secretary'),
  ('00000000-0000-4000-a000-000000000009', '00000000-0000-4000-a000-000000000009', 'bee.admin', 'BEE Admin'),
  ('00000000-0000-4000-a000-000000000010', '00000000-0000-4000-a000-000000000010', 'bee.helpdesk', 'BEE Helpdesk'),
  ('00000000-0000-4000-a000-000000000011', '00000000-0000-4000-a000-000000000011', 'bee.auditor', 'BEE Auditor'),
  ('00000000-0000-4000-a000-000000000012', '00000000-0000-4000-a000-000000000012', 'sda.officer', 'SDA Officer'),
  ('00000000-0000-4000-a000-000000000013', '00000000-0000-4000-a000-000000000013', 'lab.officer', 'Lab Officer'),
  ('00000000-0000-4000-a000-000000000015', '00000000-0000-4000-a000-000000000015', 'inactive.role', 'Inactive Role'),
  ('00000000-0000-4000-a000-000000000016', '00000000-0000-4000-a000-000000000016', 'role.mismatch', 'Role Mismatch')
ON CONFLICT (id) DO UPDATE SET keycloak_subject = EXCLUDED.keycloak_subject, username = EXCLUDED.username, display_name = EXCLUDED.display_name, status = 'active';
INSERT INTO organisation_membership (user_id, organisation_id) VALUES
  ('00000000-0000-4000-a000-000000000001', '00000000-0000-4000-b000-000000000001'),
  ('00000000-0000-4000-a000-000000000002', '00000000-0000-4000-b000-000000000002'),
  ('00000000-0000-4000-a000-000000000003', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000004', '00000000-0000-4000-b000-000000000004'),
  ('00000000-0000-4000-a000-000000000005', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000006', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000007', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000008', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000009', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000010', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000011', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000012', '00000000-0000-4000-b000-000000000005'),
  ('00000000-0000-4000-a000-000000000013', '00000000-0000-4000-b000-000000000006'),
  ('00000000-0000-4000-a000-000000000015', '00000000-0000-4000-b000-000000000003'),
  ('00000000-0000-4000-a000-000000000016', '00000000-0000-4000-b000-000000000003')
ON CONFLICT (user_id, organisation_id) DO UPDATE SET active = true;
INSERT INTO role_assignment (user_id, role, scope, active) VALUES
  ('00000000-0000-4000-a000-000000000001', 'manufacturer', 'own-org', true),
  ('00000000-0000-4000-a000-000000000002', 'agency', 'own-org', true),
  ('00000000-0000-4000-a000-000000000003', 'finance', 'all', true),
  ('00000000-0000-4000-a000-000000000004', 'iame', 'assigned', true),
  ('00000000-0000-4000-a000-000000000005', 'reviewer', 'assigned', true),
  ('00000000-0000-4000-a000-000000000006', 'programme', 'all', true),
  ('00000000-0000-4000-a000-000000000007', 'director', 'all', true),
  ('00000000-0000-4000-a000-000000000008', 'secretary', 'all', true),
  ('00000000-0000-4000-a000-000000000009', 'admin', 'all', true),
  ('00000000-0000-4000-a000-000000000010', 'helpdesk', 'all', true),
  ('00000000-0000-4000-a000-000000000011', 'auditor', 'all', true),
  ('00000000-0000-4000-a000-000000000012', 'sda', 'assigned', true),
  ('00000000-0000-4000-a000-000000000013', 'laboratory', 'assigned', true),
  ('00000000-0000-4000-a000-000000000015', 'reviewer', 'assigned', false),
  ('00000000-0000-4000-a000-000000000016', 'auditor', 'all', true)
ON CONFLICT (user_id, role) DO UPDATE SET scope = EXCLUDED.scope, active = EXCLUDED.active;
-- WP04.1 effective-dated masters: synthetic or provisional, none BEE-approved; no official fee or star rating.
-- Inserted once per (rule_key, version); a stored version that differs from the fixture fails the seed.
INSERT INTO master_category (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, name) VALUES
  ('RAC'::text, 1::integer, '2026-01-01'::date, NULL::date, 'FIRST_SLICE.md §1 (slice category); BEE category list not yet consulted'::text, 'provisional'::text, 'Local slice category only'::text, NULL::text, 'Room air conditioner'::text)
ON CONFLICT (rule_key, version) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('RAC'::text, 1::integer, '2026-01-01'::date, NULL::date, 'FIRST_SLICE.md §1 (slice category); BEE category list not yet consulted'::text, 'provisional'::text, 'Local slice category only'::text, NULL::text, 'Room air conditioner'::text)
) AS f (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, name) JOIN master_category m ON m.rule_key = f.rule_key AND m.version = f.version
  WHERE (m.effective_from, m.effective_to, m.source_reference, m.verification_status, m.note, m.legacy_id, m.name) IS DISTINCT FROM (f.effective_from, f.effective_to, f.source_reference, f.verification_status, f.note, f.legacy_id, f.name)) THEN
  RAISE EXCEPTION 'master_category: a stored version differs from the fixture; versions are immutable, add a new version instead'; END IF; END $$;
INSERT INTO master_standard (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, purpose, standard_code, title, edition) VALUES
  ('RAC:performance_test'::text, 1::integer, '2026-01-01'::date, '2026-07-01'::date, 'Synthetic local example; the applicable standard is BEE decision M2'::text, 'synthetic'::text, 'Stand-in code, not a real standard'::text, NULL::text, 'RAC'::text, 'performance_test'::text, 'SYN-RAC-PERF'::text, 'Synthetic RAC performance test standard'::text, 'synthetic-2025'::text),
  ('RAC:performance_test'::text, 2::integer, '2026-07-01'::date, NULL::date, 'Synthetic local example; the applicable standard is BEE decision M2'::text, 'synthetic'::text, 'Stand-in code, not a real standard'::text, NULL::text, 'RAC'::text, 'performance_test'::text, 'SYN-RAC-PERF'::text, 'Synthetic RAC performance test standard'::text, 'synthetic-2026'::text)
ON CONFLICT (rule_key, version) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('RAC:performance_test'::text, 1::integer, '2026-01-01'::date, '2026-07-01'::date, 'Synthetic local example; the applicable standard is BEE decision M2'::text, 'synthetic'::text, 'Stand-in code, not a real standard'::text, NULL::text, 'RAC'::text, 'performance_test'::text, 'SYN-RAC-PERF'::text, 'Synthetic RAC performance test standard'::text, 'synthetic-2025'::text),
  ('RAC:performance_test'::text, 2::integer, '2026-07-01'::date, NULL::date, 'Synthetic local example; the applicable standard is BEE decision M2'::text, 'synthetic'::text, 'Stand-in code, not a real standard'::text, NULL::text, 'RAC'::text, 'performance_test'::text, 'SYN-RAC-PERF'::text, 'Synthetic RAC performance test standard'::text, 'synthetic-2026'::text)
) AS f (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, purpose, standard_code, title, edition) JOIN master_standard m ON m.rule_key = f.rule_key AND m.version = f.version
  WHERE (m.effective_from, m.effective_to, m.source_reference, m.verification_status, m.note, m.legacy_id, m.category_code, m.purpose, m.standard_code, m.title, m.edition) IS DISTINCT FROM (f.effective_from, f.effective_to, f.source_reference, f.verification_status, f.note, f.legacy_id, f.category_code, f.purpose, f.standard_code, f.title, f.edition)) THEN
  RAISE EXCEPTION 'master_standard: a stored version differs from the fixture; versions are immutable, add a new version instead'; END IF; END $$;
INSERT INTO master_lab_accreditation (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, laboratory_code, category_code, accreditation_body, certificate_ref, accreditation_status) VALUES
  ('LAB:RAC'::text, 1::integer, '2026-01-01'::date, '2026-06-01'::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Synthetic accreditation history'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0001'::text, 'active'::text),
  ('LAB:RAC'::text, 2::integer, '2026-06-01'::date, '2026-07-01'::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Synthetic accreditation history'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0002'::text, 'suspended'::text),
  ('LAB:RAC'::text, 3::integer, '2026-08-01'::date, NULL::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Re-accredited after a synthetic gap (2026-07-01 to 2026-08-01)'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0003'::text, 'active'::text)
ON CONFLICT (rule_key, version) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('LAB:RAC'::text, 1::integer, '2026-01-01'::date, '2026-06-01'::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Synthetic accreditation history'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0001'::text, 'active'::text),
  ('LAB:RAC'::text, 2::integer, '2026-06-01'::date, '2026-07-01'::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Synthetic accreditation history'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0002'::text, 'suspended'::text),
  ('LAB:RAC'::text, 3::integer, '2026-08-01'::date, NULL::date, 'Synthetic local example; no accreditation body was consulted'::text, 'synthetic'::text, 'Re-accredited after a synthetic gap (2026-07-01 to 2026-08-01)'::text, NULL::text, 'LAB'::text, 'RAC'::text, 'SYN-ACCREDITATION-BODY'::text, 'SYN-LAB-RAC-0003'::text, 'active'::text)
) AS f (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, laboratory_code, category_code, accreditation_body, certificate_ref, accreditation_status) JOIN master_lab_accreditation m ON m.rule_key = f.rule_key AND m.version = f.version
  WHERE (m.effective_from, m.effective_to, m.source_reference, m.verification_status, m.note, m.legacy_id, m.laboratory_code, m.category_code, m.accreditation_body, m.certificate_ref, m.accreditation_status) IS DISTINCT FROM (f.effective_from, f.effective_to, f.source_reference, f.verification_status, f.note, f.legacy_id, f.laboratory_code, f.category_code, f.accreditation_body, f.certificate_ref, f.accreditation_status)) THEN
  RAISE EXCEPTION 'master_lab_accreditation: a stored version differs from the fixture; versions are immutable, add a new version instead'; END IF; END $$;
INSERT INTO master_fee_rule (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, application_type, amount_inr) VALUES
  ('RAC:new_model'::text, 1::integer, '2026-01-01'::date, '2026-10-01'::date, 'V2 local seed fee_rule RAC-DEMO (local placeholder; no source)'::text, 'synthetic'::text, 'Synthetic local amount only; BEE fee decision pending'::text, 'RAC-DEMO'::text, 'RAC'::text, 'new_model'::text, '1000.00'::numeric),
  ('RAC:new_model'::text, 2::integer, '2026-10-01'::date, NULL::date, 'FIRST_SLICE.md provisional decision D6, citing DDD §5.3 (gap G08); not confirmed by BEE'::text, 'provisional'::text, 'Provisional local amount from D6; supersedes the ₹1,000 placeholder for dates from 2026-10-01; BEE decision D6 pending'::text, NULL::text, 'RAC'::text, 'new_model'::text, '24000.00'::numeric)
ON CONFLICT (rule_key, version) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('RAC:new_model'::text, 1::integer, '2026-01-01'::date, '2026-10-01'::date, 'V2 local seed fee_rule RAC-DEMO (local placeholder; no source)'::text, 'synthetic'::text, 'Synthetic local amount only; BEE fee decision pending'::text, 'RAC-DEMO'::text, 'RAC'::text, 'new_model'::text, '1000.00'::numeric),
  ('RAC:new_model'::text, 2::integer, '2026-10-01'::date, NULL::date, 'FIRST_SLICE.md provisional decision D6, citing DDD §5.3 (gap G08); not confirmed by BEE'::text, 'provisional'::text, 'Provisional local amount from D6; supersedes the ₹1,000 placeholder for dates from 2026-10-01; BEE decision D6 pending'::text, NULL::text, 'RAC'::text, 'new_model'::text, '24000.00'::numeric)
) AS f (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, application_type, amount_inr) JOIN master_fee_rule m ON m.rule_key = f.rule_key AND m.version = f.version
  WHERE (m.effective_from, m.effective_to, m.source_reference, m.verification_status, m.note, m.legacy_id, m.category_code, m.application_type, m.amount_inr) IS DISTINCT FROM (f.effective_from, f.effective_to, f.source_reference, f.verification_status, f.note, f.legacy_id, f.category_code, f.application_type, f.amount_inr)) THEN
  RAISE EXCEPTION 'master_fee_rule: a stored version differs from the fixture; versions are immutable, add a new version instead'; END IF; END $$;
INSERT INTO master_rating_formula (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, formula_label, inputs, definition, computation_allowed) VALUES
  ('RAC:star_rating'::text, 1::integer, '2026-01-01'::date, NULL::date, 'V2 local seed rating_formula RAC-STAR-DEMO (FIRST_SLICE.md D3 placeholder)'::text, 'synthetic'::text, 'Placeholder only; no official rating may be computed'::text, 'RAC-STAR-DEMO'::text, 'RAC'::text, '0-unverified'::text, '[]'::jsonb, '{}'::jsonb, false::boolean)
ON CONFLICT (rule_key, version) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('RAC:star_rating'::text, 1::integer, '2026-01-01'::date, NULL::date, 'V2 local seed rating_formula RAC-STAR-DEMO (FIRST_SLICE.md D3 placeholder)'::text, 'synthetic'::text, 'Placeholder only; no official rating may be computed'::text, 'RAC-STAR-DEMO'::text, 'RAC'::text, '0-unverified'::text, '[]'::jsonb, '{}'::jsonb, false::boolean)
) AS f (rule_key, version, effective_from, effective_to, source_reference, verification_status, note, legacy_id, category_code, formula_label, inputs, definition, computation_allowed) JOIN master_rating_formula m ON m.rule_key = f.rule_key AND m.version = f.version
  WHERE (m.effective_from, m.effective_to, m.source_reference, m.verification_status, m.note, m.legacy_id, m.category_code, m.formula_label, m.inputs, m.definition, m.computation_allowed) IS DISTINCT FROM (f.effective_from, f.effective_to, f.source_reference, f.verification_status, f.note, f.legacy_id, f.category_code, f.formula_label, f.inputs, f.definition, f.computation_allowed)) THEN
  RAISE EXCEPTION 'master_rating_formula: a stored version differs from the fixture; versions are immutable, add a new version instead'; END IF; END $$;
-- WP04.2a brand ownership and agency authorisation: synthetic only; not BEE-approved.
-- Inserted once per id; a stored row that differs from the fixture fails the seed.
INSERT INTO brand (id, name, owner_organisation_id, status, source_reference, verification_status, note) VALUES
  ('00000000-0000-4000-d000-000000000001', 'Nova Cool', '00000000-0000-4000-b000-000000000001', 'active', 'FIRST_SLICE.md §1 Nova Cool brand (synthetic local seed); not BEE-approved', 'synthetic', 'Synthetic manufacturer brand for local brand-ownership checks')
ON CONFLICT (id) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('00000000-0000-4000-d000-000000000001'::uuid, 'Nova Cool'::text, '00000000-0000-4000-b000-000000000001'::uuid, 'active'::text, 'FIRST_SLICE.md §1 Nova Cool brand (synthetic local seed); not BEE-approved'::text, 'synthetic'::text, 'Synthetic manufacturer brand for local brand-ownership checks'::text)
) AS f (id, name, owner_organisation_id, status, source_reference, verification_status, note) JOIN brand b ON b.id = f.id
  WHERE (b.name, b.owner_organisation_id, b.status, b.source_reference, b.verification_status, b.note) IS DISTINCT FROM (f.name, f.owner_organisation_id, f.status, f.source_reference, f.verification_status, f.note)) THEN
  RAISE EXCEPTION 'brand: a stored row differs from the fixture'; END IF; END $$;
INSERT INTO agency_authorisation (id, agency_organisation_id, principal_organisation_id, brand_id, valid_from, valid_to, status, source_reference, verification_status, note) VALUES
  ('00000000-0000-4000-e000-000000000001', '00000000-0000-4000-b000-000000000002', '00000000-0000-4000-b000-000000000001', '00000000-0000-4000-d000-000000000001', '2026-01-01'::date, NULL::date, 'active', 'FIRST_SLICE.md §1 PixelCert authorised for Nova Cool (synthetic); not BEE-approved', 'synthetic', 'Synthetic agency authorisation for half-open period resolution tests')
ON CONFLICT (id) DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM (VALUES
  ('00000000-0000-4000-e000-000000000001'::uuid, '00000000-0000-4000-b000-000000000002'::uuid, '00000000-0000-4000-b000-000000000001'::uuid, '00000000-0000-4000-d000-000000000001'::uuid, '2026-01-01'::date, NULL::date, 'active'::text, 'FIRST_SLICE.md §1 PixelCert authorised for Nova Cool (synthetic); not BEE-approved'::text, 'synthetic'::text, 'Synthetic agency authorisation for half-open period resolution tests'::text)
) AS f (id, agency_organisation_id, principal_organisation_id, brand_id, valid_from, valid_to, status, source_reference, verification_status, note) JOIN agency_authorisation a ON a.id = f.id
  WHERE (a.agency_organisation_id, a.principal_organisation_id, a.brand_id, a.valid_from, a.valid_to, a.status, a.source_reference, a.verification_status, a.note) IS DISTINCT FROM (f.agency_organisation_id, f.principal_organisation_id, f.brand_id, f.valid_from, f.valid_to, f.status, f.source_reference, f.verification_status, f.note)) THEN
  RAISE EXCEPTION 'agency_authorisation: a stored row differs from the fixture'; END IF; END $$;
-- WP02.2 scope fixtures: seeded states only; version reset to 0 on every seed.
INSERT INTO model_application (id, reference, organisation_id, brand_name, category, model_number, state, version) VALUES
  ('00000000-0000-4000-c000-000000000001', 'LOCAL-MA-0001', '00000000-0000-4000-b000-000000000001', 'Nova Cool', 'RAC', 'NC-RAC-12D', 'draft', 0),
  ('00000000-0000-4000-c000-000000000002', 'LOCAL-MA-0002', '00000000-0000-4000-b000-000000000001', 'Nova Cool', 'RAC', 'NC-RAC-18F', 'fee_due', 0),
  ('00000000-0000-4000-c000-000000000003', 'LOCAL-MA-0003', '00000000-0000-4000-b000-000000000002', 'Aurora Air (synthetic principal)', 'RAC', 'AU-RAC-15X', 'iame_scrutiny', 0),
  ('00000000-0000-4000-c000-000000000004', 'LOCAL-MA-0004', '00000000-0000-4000-b000-000000000001', 'Nova Cool', 'RAC', 'NC-RAC-24H', 'bee_scrutiny', 0)
ON CONFLICT (id) DO UPDATE SET reference = EXCLUDED.reference, organisation_id = EXCLUDED.organisation_id, brand_name = EXCLUDED.brand_name, model_number = EXCLUDED.model_number, state = EXCLUDED.state, version = 0;
INSERT INTO assignment (user_id, subject_type, subject_id, stage, active) VALUES
  ('00000000-0000-4000-a000-000000000004', 'model_application', '00000000-0000-4000-c000-000000000003', 'iame_scrutiny', true),
  ('00000000-0000-4000-a000-000000000005', 'model_application', '00000000-0000-4000-c000-000000000004', 'bee_scrutiny', false)
ON CONFLICT (user_id, subject_type, subject_id, stage) DO UPDATE SET active = EXCLUDED.active;
INSERT INTO seed_run (seed_version) VALUES ('rt1-local-v2'), ('wp02.2-local-v1'), ('wp04.1-masters-v1'), ('wp04.2-brand-auth-v1') ON CONFLICT (seed_version) DO NOTHING;
COMMIT;
