/* eslint-disable */
/**
 * Local test authenticator for the WP02.3 TOTP policy. Secrets are generated by Keycloak
 * during real CONFIGURE_TOTP enrollment and kept only in git-ignored .local/run/totp/
 * (mode 0600). Codes are RFC 6238 (HmacSHA1, 6 digits, 30 s), matching the realm policy.
 * Keycloak rejects a reused code, so each user's 30-second steps are handed out once.
 *
 *   node scripts/local/totp.cjs token <username>    print an access token (bee-local-check, with OTP)
 *   node scripts/local/totp.cjs enroll <username>   enroll a user who has no OTP credential yet
 *   node scripts/local/totp.cjs logout <username>   end the user's Keycloak sessions (issued JWTs stay valid to expiry)
 *
 * Seeded users (local/generate-fixtures.cjs) are protected: routine checks use disposable
 * twins (scripts/local/test-identities.cjs). An existing OTP credential is never replaced;
 * when its secret is not in the local store, the helper reports that and stops. Removing
 * a seeded user's credential or sessions, or enrolling one, needs { allowProtected: true },
 * which only the explicit CLI commands pass. BEE_TOTP_DIR overrides the store directory.
 */
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const env = (k, d) => process.env[k] || d;
const KC = `http://127.0.0.1:${env("BEE_KC_PORT", "8180")}`;
const REALM = env("BEE_REALM", "bee-local");
const ISSUER = `${KC}/realms/${REALM}`;
const PASSWORD = env("BEE_DEV_USER_PASSWORD", "bee-local-dev");
const ADMIN_PASSWORD = env("BEE_KC_ADMIN_PASSWORD", "bee-local-admin");
const DIR = env("BEE_TOTP_DIR", path.join(__dirname, "../../.local/run/totp"));
const PROTECTED = new Set(require("../../local/generate-fixtures.cjs").USERS.map((u) => u.username));
function guard(u, opts, what) {
  if (PROTECTED.has(u) && !opts?.allowProtected) throw new Error(`refusing to ${what} seeded user ${u}; routine checks use disposable test identities`);
}
const PERIOD = 30;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/* ---------- RFC 6238 ---------- */
function hotp(secret, counter) {
  const msg = Buffer.alloc(8);
  msg.writeBigUInt64BE(BigInt(counter));
  const h = crypto.createHmac("sha1", Buffer.from(secret, "utf8")).update(msg).digest();
  const o = h[h.length - 1] & 0xf;
  return String((h.readUInt32BE(o) & 0x7fffffff) % 1_000_000).padStart(6, "0");
}
const currentStep = () => Math.floor(Date.now() / 1000 / PERIOD);

/* ---------- ignored local state ---------- */
const file = (u) => path.join(DIR, `${u}.json`);
function load(u) {
  try { return JSON.parse(fs.readFileSync(file(u), "utf8")); } catch { return null; }
}
function save(u, data) {
  fs.mkdirSync(DIR, { recursive: true, mode: 0o700 });
  fs.writeFileSync(file(u), JSON.stringify(data), { mode: 0o600 });
}

/**
 * A code for a step this user has not used yet: the current step, else the next one
 * (inside the realm's look-around window of 1), else wait for the period to roll.
 */
async function nextCode(u) {
  const st = load(u);
  if (!st) throw new Error(`no local authenticator for ${u}`);
  for (;;) {
    const now = currentStep();
    const s = Math.max(now, (st.lastStep ?? -1) + 1);
    if (s <= now + 1) {
      st.lastStep = s;
      save(u, st);
      return hotp(st.secret, s);
    }
    await sleep(Math.max(250, ((now + 1) * PERIOD - Date.now() / 1000) * 1000 + 300));
  }
}
/** A syntactically valid code that is not accepted at any step in the window. */
function wrongCode(u) {
  const st = load(u);
  const now = currentStep();
  const valid = new Set([-1, 0, 1].map((d) => hotp(st.secret, now + d)));
  for (let i = 0; ; i++) { const c = String((123456 + i * 7919) % 1_000_000).padStart(6, "0"); if (!valid.has(c)) return c; }
}

/* ---------- Keycloak pages ---------- */
const decode = (s) => s.replace(/&amp;/g, "&").replace(/&#x3D;/g, "=").replace(/&quot;/g, '"').replace(/&#61;/g, "=");
const formAction = (body, id) => {
  const m = new RegExp(`<form[^>]*id="${id}"[^>]*action="([^"]+)"`).exec(body) || new RegExp(`<form[^>]*action="([^"]+)"[^>]*id="${id}"`).exec(body);
  return m ? decode(m[1]) : null;
};
/** Which Keycloak page this is: login, totp-setup (enrollment), otp (challenge), or other. */
function page(body) {
  const setup = formAction(body, "kc-totp-settings-form");
  if (setup) return { kind: "totp-setup", action: setup, secret: /name="totpSecret"[^>]*value="([^"]+)"/.exec(body)?.[1] || /value="([^"]+)"[^>]*name="totpSecret"/.exec(body)?.[1] };
  const otp = formAction(body, "kc-otp-login-form");
  if (otp) return { kind: "otp", action: otp };
  const login = formAction(body, "kc-form-login");
  if (login) return { kind: "login", action: login };
  return { kind: "other" };
}
const errorText = (body) => decode((/id="input-error[^"]*"[^>]*>\s*<span[^>]*>\s*([^<]+)/.exec(body) || /id="input-error[^"]*"[^>]*>\s*([^<]+)/.exec(body) || /class="[^"]*alert-error[^"]*"[\s\S]*?<span[^>]*kc-feedback-text[^>]*>([^<]+)/.exec(body) || /kc-feedback-text">([^<]+)/.exec(body) || [])[1] || "").trim();

const form = (o) => ({ method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(o) });

/**
 * Drives a Keycloak browser login to its redirect. `req(url, init)` must keep cookies and
 * not follow redirects, returning { status, location, body }. Enrolls when Keycloak asks.
 */
async function completeLogin(req, first, username, { password = PASSWORD, onPage } = {}) {
  let r = first;
  for (let i = 0; i < 8; i++) {
    if (r.status === 302 || r.status === 303) {
      const next = new URL(r.location, ISSUER);
      if (next.origin === KC && next.pathname.includes("/login-actions/")) { r = await req(next.toString()); continue; }
      return { location: r.location, response: r };
    }
    const p = page(r.body);
    if (onPage) onPage(p, r);
    if (p.kind === "login") r = await req(p.action, form({ username, password, credentialId: "" }));
    else if (p.kind === "totp-setup") {
      const st = { secret: p.secret, enrolledAt: new Date().toISOString(), lastStep: -1 };
      save(username, st);
      r = await req(p.action, form({ totp: await nextCode(username), totpSecret: p.secret, userLabel: "local-check", "logout-sessions": "on" }));
    } else if (p.kind === "otp") r = await req(p.action, form({ otp: await nextCode(username), login: "Sign In" }));
    else throw new Error(`unexpected Keycloak page for ${username} (HTTP ${r.status}): ${errorText(r.body) || r.body.slice(0, 120)}`);
  }
  throw new Error(`login for ${username} did not finish`);
}

/* ---------- admin helpers ---------- */
async function adminToken() {
  const r = await fetch(`${KC}/realms/master/protocol/openid-connect/token`, { method: "POST", body: new URLSearchParams({ grant_type: "password", client_id: "admin-cli", username: "admin", password: ADMIN_PASSWORD }) });
  return (await r.json()).access_token;
}
async function admin(pathname, init = {}) {
  const r = await fetch(`${KC}/admin/realms/${REALM}${pathname}`, { ...init, headers: { Authorization: `Bearer ${await adminToken()}`, ...(init.headers || {}) } });
  const t = await r.text();
  try { return JSON.parse(t); } catch { return t; }
}
// Keycloak answers a missing user with {"error":"User not found"}; fail by name rather than as "x.filter is not a function".
async function adminList(pathname) {
  const r = await admin(pathname);
  if (!Array.isArray(r)) throw new Error(`Keycloak admin GET ${pathname} returned ${JSON.stringify(r).slice(0, 120)}, not a list`);
  return r;
}
async function userId(u) {
  const id = (await adminList(`/users?username=${encodeURIComponent(u)}&exact=true`))[0]?.id;
  if (!id) throw new Error(`Keycloak user ${u} not found (a concurrent local run may have torn down the test identities)`);
  return id;
}
const otpCredentials = async (u) => (await adminList(`/users/${await userId(u)}/credentials`)).filter((c) => c.type === "otp");
async function removeOtp(u, opts) {
  guard(u, opts, "remove the OTP credential of");
  const id = await userId(u);
  for (const c of await otpCredentials(u)) await admin(`/users/${id}/credentials/${c.id}`, { method: "DELETE" });
  await admin(`/users/${id}/logout`, { method: "POST" });
  try { fs.unlinkSync(file(u)); } catch {}
}
async function logoutUser(u, opts) {
  guard(u, opts, "end the Keycloak sessions of");
  return admin(`/users/${await userId(u)}/logout`, { method: "POST" });
}

/* ---------- jar-backed request, for enrollment outside the portal ---------- */
function cookieReq() {
  const jar = new Map();
  return async (url, init = {}) => {
    const host = new URL(url).host;
    const cookie = [...jar.entries()].filter(([k]) => k.startsWith(host + "|")).map(([k, v]) => `${k.split("|")[1]}=${v}`).join("; ");
    const res = await fetch(url, { ...init, headers: { ...(init.headers || {}), ...(cookie ? { Cookie: cookie } : {}) }, redirect: "manual" });
    for (const c of res.headers.getSetCookie()) { const [pair] = c.split(";"); const i = pair.indexOf("="); jar.set(`${host}|${pair.slice(0, i)}`, pair.slice(i + 1)); }
    return { status: res.status, location: res.headers.get("location"), body: await res.text() };
  };
}

/** An existing OTP credential whose secret this store does not hold. Never replaced. */
class UnusableCredential extends Error {}

/**
 * Returns false when the stored secret matches the user's single Keycloak OTP credential.
 * With no OTP credential, enrolls through Keycloak's own account-console login and ends
 * that Keycloak session. With a credential this store cannot use (enrolled elsewhere, or
 * the local file is missing or stale), throws UnusableCredential and changes nothing.
 */
async function ensureEnrolled(u, opts) {
  const st = load(u);
  const creds = await otpCredentials(u);
  if (st && creds.length === 1 && st.credentialId === creds[0].id) return false;
  if (creds.length) throw new UnusableCredential(`${u} has ${creds.length} OTP credential(s) (${creds.map((c) => c.id).join(", ")}) but no matching secret in ${DIR}; not replaced. Use the user's own authenticator, or delete the credential explicitly in the Keycloak admin console first.`);
  guard(u, opts, "enroll");
  const req = cookieReq();
  const verifier = crypto.randomBytes(32).toString("base64url");
  const q = new URLSearchParams({ client_id: "account-console", redirect_uri: `${ISSUER}/account/`, response_type: "code", scope: "openid", state: crypto.randomBytes(8).toString("hex"), nonce: crypto.randomBytes(8).toString("hex"), code_challenge: crypto.createHash("sha256").update(verifier).digest("base64url"), code_challenge_method: "S256" });
  const done = await completeLogin(req, await req(`${ISSUER}/protocol/openid-connect/auth?${q}`), u);
  if (!done.location?.startsWith(`${ISSUER}/account/`)) throw new Error(`enrollment for ${u} ended at ${done.location}`);
  const after = await otpCredentials(u);
  save(u, { ...load(u), credentialId: after[0]?.id });
  await logoutUser(u, { allowProtected: true });
  return true;
}
/** After a portal enrollment, record which Keycloak credential the stored secret belongs to. */
async function recordCredential(u) {
  const c = await otpCredentials(u);
  save(u, { ...load(u), credentialId: c[0]?.id });
}

/** Password grant through the local check client; OTP is required by the realm. */
async function passwordGrant(u, { otp, password = PASSWORD } = {}) {
  const body = { grant_type: "password", client_id: "bee-local-check", username: u, password };
  if (otp !== null) body.totp = otp ?? (await nextCode(u));
  const r = await fetch(`${ISSUER}/protocol/openid-connect/token`, { method: "POST", body: new URLSearchParams(body) });
  return { status: r.status, json: await r.json() };
}
async function accessToken(u, opts) {
  await ensureEnrolled(u, opts);
  const r = await passwordGrant(u);
  if (!r.json.access_token) throw new Error(`no token for ${u}: ${JSON.stringify(r.json)}`);
  return r.json.access_token;
}

module.exports = { hotp, currentStep, save, nextCode, wrongCode, page, errorText, completeLogin, ensureEnrolled, recordCredential, removeOtp, logoutUser, otpCredentials, passwordGrant, accessToken, load, admin, adminToken, userId, UnusableCredential, PROTECTED, DIR };

if (require.main === module) {
  const [cmd, u] = process.argv.slice(2);
  (async () => {
    if (cmd === "token") process.stdout.write(await accessToken(u));
    else if (cmd === "enroll") console.log((await ensureEnrolled(u, { allowProtected: true })) ? `enrolled ${u}` : `${u} already enrolled`);
    else if (cmd === "logout") await logoutUser(u, { allowProtected: true });
    else { console.error("usage: totp.cjs token|enroll|logout <username>"); process.exit(2); }
  })().catch((e) => { console.error(e.message); process.exit(1); });
}
